inherit_from: .rubocop_todo.yml

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Metrics/BlockLength:
  Exclude:
    - 'Guardfile'
    - 'spec/**/*'

Style:
  Exclude:
    - 'db/schema.rb'
