AllCops:
  Exclude:
    - 'db/**/*'

Layout/EmptyLinesAroundBlockBody:
  Exclude:
    - 'db/schema.rb'

Metrics/AbcSize:
  Max: 18

Metrics/BlockLength:
  Max: 30

Metrics/MethodLength:
  Max: 11

Metrics/LineLength:
  Max: 214

Style/MixinUsage:
  Exclude:
    - 'bin/setup'
    - 'bin/update'
